#!/bin/bash

export JAVA_OPTS="-Dspecs2.color=false -Dsbt.log.format=true -Dsbt.log.noformat=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128 $JAVA_OPTS"

#echo "sbt -Dsbt.log.noformat=true -ivy $WORKSPACE vehiclesPresentationCommon/clean clean vehiclesPresentationCommon/test test dist publish"

sbt -Dsbt.log.noformat=true -ivy $WORKSPACE vehiclesPresentationCommon/clean clean vehiclesPresentationCommon/test test dist publish

./jenkins_job_build_rpm
