package uk.gov.dvla.vehicles.presentation.common.clientsidesession

import java.security.SecureRandom

object ByteGenerator {

  /**
    * Creates an array of randomly generated bytes
    *
    * @param numberOfBytes the size of the random byte array
    * @return a random byte array whose size is specified by the numberOfBytes argument
    */
  def getSecureRandomBytes(numberOfBytes: Int): Array[Byte] = {
    val bytes = new Array[Byte](numberOfBytes)
    val random = new SecureRandom()
    random.nextBytes(bytes)
    bytes
  }
}